Allow CRLF at the start of multiline strings
gren-lang/compiler pull request #255
Opened 2024-08-02 10:03 UTC by mbartlett21

This should fix #254.

2024-08-03 04:53 UTC, robinheghan requested changes
Good first attempt, but I think we can do better.

Also, please add your name to the CONTRIBUTORS file, if it isn't there already.

2024-08-03 04:53 UTC, robinheghan commented on compiler/src/Parse/String.hs
> +       in if word == 0x0A || word == 0x0D {- \n or \r -}
This should probably be rewritten to check for the existance of `\r\n` and not just `\r`. You should probably also make a similar change to `multiStringBody` if you want this sequence to be valid within multistrings as well.

2024-08-03 04:53 UTC, robinheghan commented on compiler/src/Reporting/Error/Syntax.hs
> +              ( D.reflow "The contents of a multiline string must start on a new line",
Good catch!

2024-08-03 04:53 UTC, robinheghan commented on tests/Parse/MultilineStringSpec.hs
> +        "\"\"\"\r\nnormal string\"\"\""
You should probably add the following tests

* A multiline string with a leading `\r` (missing `\n`) shouldn't be allowed
* `\r\n` should be allowed in the middle of a multi-string as well

2024-08-09 07:25 UTC, robinheghan commented
Code formatting check fails.

To apply correct code formatting, install `ormolu` and run `ormolu --mode inplace $(git ls-files '*.hs')`

2024-08-09 07:27 UTC, mbartlett21 commented
@robinheghan 
I've added another test for if it doesn't end with a newline, which was previously wrong.
I.e.
```
"""testing
testing"""
```
previously dropped the newline

2024-08-09 20:35 UTC, robinheghan approved these changes
Thank you for this <3

2024-08-09 20:35 UTC, merged